### ISSUE TITLE
Error output for completed observable

### ISSUE THREAD

**Issue by blobor** [just-jeb/jest-marbles#101] opened 2019-03-12 03:21 UTC
Given code snipped produces unreadable (as expected) error output
```javascript
const { merge } = require('rxjs/operators')
const { cold, hot } = require('jest-marbles');

describe("RxJS", () => {
    it('Should merge two hot observables and start emitting from the subscription point', () => {
        const e1 = hot('----a--^--b-------c--|', {a: 0});
        const e2 = hot('  ---d-^--e---------f-----|', {a: 0});
        const expected = cold('--d-(be)----c-f-----|', {a: 0});
        //                       ^--- added this so assertion fails

        expect(e1.pipe(merge(e2))).toBeObservable(expected);
    });
})
```
**jest-marbles**: 2.3.0
**rxjs**: 6.4.0
**Output:**
```bash
  ● RxJS › Should merge two hot observables and start emitting from the subscription point

    expect(received).toBeNotifications(expected)

    Expected notifications to be:
      [{"frame": 20, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 40, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 40, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 120, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 140, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 200, "notification": {"error": undefined, "hasValue": false, "kind": "C", "value": undefined}}]
    But got:
      [{"frame": 30, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 30, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 110, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 130, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": undefined}}, {"frame": 190, "notification": {"error": undefined, "hasValue": false, "kind": "C", "value": undefined}}]

    Difference:

    - Expected
    + Received

      Array [
        Object {
    -     "frame": 20,
    +     "frame": 30,
          "notification": Notification {
            "error": undefined,
            "hasValue": true,
            "kind": "N",
            "value": undefined,
          },
        },
        Object {
    -     "frame": 40,
    +     "frame": 30,
          "notification": Notification {
            "error": undefined,
            "hasValue": true,
            "kind": "N",
            "value": undefined,
          },
        },
        Object {
    -     "frame": 40,
    +     "frame": 110,
          "notification": Notification {
            "error": undefined,
            "hasValue": true,
            "kind": "N",
            "value": undefined,
          },
        },
        Object {
    -     "frame": 120,
    +     "frame": 130,
          "notification": Notification {
            "error": undefined,
            "hasValue": true,
            "kind": "N",
            "value": undefined,
          },
        },
        Object {
    -     "frame": 140,
    +     "frame": 190,
          "notification": Notification {
            "error": undefined,
    -       "hasValue": true,
    -       "kind": "N",
    -       "value": undefined,
    -     },
    -   },
    -   Object {
    -     "frame": 200,
    -     "notification": Notification {
    -       "error": undefined,
            "hasValue": false,
            "kind": "C",
            "value": undefined,
          },
        },
      ]

      at TestScheduler.assertDeepEqual (node_modules/jest-marbles/umd/webpack:/JestMarbles/src/rxjs/assert-deep-equal.ts:29:20)
      at Object.<anonymous> (node_modules/jest-marbles/umd/webpack:/JestMarbles/index.ts:67:19)
```

Looks like a root cause of the issue is in this line https://github.com/meltedspark/jest-marbles/blob/29360098dea0ea95d7b714c75d1be0d5de8a4b15/src/jest/custom-matchers.ts#L13
Completion `notification` produces `undefined` value which fails check in `containNonCharacterValue` function.

**Comment by meltedspark** [comment] 2019-03-12 07:02
I don't think the root cause is within the `isCharacter` function.  
The logic is pretty straight forward: if all the values are characters then marblize, otherwise don't
.  
But there is definitely a problem - why all the values are `undefined`? Would you mind trying the same without `{a : 0}`? Just plain marbles string?

**Comment by blobor** [comment] 2019-03-12 15:22
> But there is definitely a problem - why all the values are undefined? Would you mind trying the same without {a : 0}? Just plain marbles string?

@meltedspark this is a copy past from https://github.com/meltedspark/jest-marbles#examples 😅

**Comment by blobor** [comment] 2019-03-12 15:26
> I don't think the root cause is within the isCharacter function.
The logic is pretty straight forward: if all the values are characters then marblize, otherwise don't

yeah, you are right.

one more example:

```javascript
it('Should concatenate two cold observables into single cold observable', () => {
        const a = cold('-a-|');
        const b = cold('-b-|');
        const expected = '-a--a-|';
        //                    ^----changed for error

        expect(a.pipe(concat(b))).toBeMarble(expected);
    });
```

**Output:**
```bash
  ● RxJS › Should concatenate two cold observables into single cold observable

    expect(received).toBeNotifications(expected)

    Expected notifications to be:
      [{"frame": 10, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": "a"}}, {"frame": 40, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": "a"}}, {"frame": 60, "notification": {"error": undefined, "hasValue": false, "kind": "C", "value": undefined}}]
    But got:
      [{"frame": 10, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": "a"}}, {"frame": 40, "notification": {"error": undefined, "hasValue": true, "kind": "N", "value": "b"}}, {"frame": 60, "notification": {"error": undefined, "hasValue": false, "kind": "C", "value": undefined}}]

    Difference:

    - Expected
    + Received

      Array [
        Object {
          "frame": 10,
          "notification": Notification {
            "error": undefined,
            "hasValue": true,
            "kind": "N",
            "value": "a",
          },
        },
        Object {
          "frame": 40,
          "notification": Notification {
            "error": undefined,
            "hasValue": true,
            "kind": "N",
    -       "value": "a",
    +       "value": "b",
          },
        },
        Object {
          "frame": 60,
          "notification": Notification {
            "error": undefined,
            "hasValue": false,
            "kind": "C",
            "value": undefined,
          },
        },
      ]

      at TestScheduler.assertDeepEqual (node_modules/jest-marbles/umd/webpack:/JestMarbles/src/rxjs/assert-deep-equal.ts:29:20)
      at Object.<anonymous> (node_modules/jest-marbles/umd/webpack:/JestMarbles/index.ts:67:19)
```

**Comment by meltedspark** [comment] 2019-03-12 20:28
Ok, got it. The issue is that marblizer predicate ignores the kind of notification. Good catch, thanks!  
The fix is on its way.

**Comment by meltedspark** [comment] 2019-03-12 20:59
Fixed in `2.3.1`

**Comment by blobor** [comment] 2019-03-14 16:19
Thanks @meltedspark

**Comment by blobor** [comment] 2019-03-29 09:40
@meltedspark So I just tested case for:
```javascript
const { merge } = require('rxjs/operators')
const { cold, hot } = require('jest-marbles');

describe("RxJS", () => {
    it('Should merge two hot observables and start emitting from the subscription point', () => {
        const e1 = hot('----a--^--b-------c--|', {a: 0});
        const e2 = hot('  ---d-^--e---------f-----|', {a: 0});
        const expected = cold('--d-(be)----c-f-----|', {a: 0});
        //                       ^--- added this so assertion fails

        expect(e1.pipe(merge(e2))).toBeObservable(expected);
    });
})
```
And still it fail to produce readable error message 🤔

But `2.3.1` definetly fixed, this case:
```javascript
it('Should concatenate two cold observables into single cold observable', () => {
      const a = cold('-a-|');
      const b = cold('-b-|');
      const expected = '-a--a-|';

      expect(a.pipe(concat(b))).toBeMarble(expected);
});

**Comment by meltedspark** [comment] 2019-03-29 09:59
Interesting, I'll take look.

**Comment by meltedspark** [comment] 2019-03-31 20:05
@blobor Hey, I'm unable to reproduce the issue. Would you mind creating a minimal reproduction repo so that I could look into this? Thanks!

**Comment by blobor** [comment] 2019-04-16 10:24
@meltedspark sorry for late response, so I created reproduction repo https://github.com/blobor/marbles-bug

just run `yarn test` :)

You should see:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/4813007/56202090-f8d3fe80-604a-11e9-9728-c622557e1068.png">

**Closed** 2019-07-18 10:57 UTC
Labels: bug, good first issue
